const mongoose = require('mongoose');

const updateShgMemberSchema = new mongoose.Schema({
  district: String,
  block: String,
  panchayat: String,
  habitation: String,
  isDeleted: { type: Boolean, default: false },
  SHGId: Number,
  MemberId: { type: Number },
  SHGName: String,
  formationDate: String,
  SHGCode: String,
  bankName: String,
  memberName: String,
  fatherName: String,
  memberAge: String,
  DOB: String,
  gender: String,
  religion: String,
  community: String,
  vulnerableCategory: String,
  education: String,
  occupation: String,
  workerCode: String,
  MSMERegNumber: String,
  isESharm: String,
  eSharmRegNumber: String,
  islivelihood: String,
  livelihoodActivities: String,
  annualIncome: String,
  PIPCategory: String,
  PIP: String,
  role: String,
  PAN: String,
  AADHAR: String,
  smartCard: String,
  contact: String,
  monthlySavings: Number,
  isVRFReceived: String,
  VRFAmount: String,
  isInsuranceRegistered: String,
  insuranceType: String,
  lastExpiryDate: String,
  branchName: String,
  IFSC: String,
  accountNumber: Number,
  familyMemberCount: String,
  annualIncomeOfFamily: String,
  isLocalBodyRepresentative: String,
  localBodyRepresentativePosition: String,
  accountType: String,
  accountStatus: String,
  totalMembers: String,
  aknowlege: String,
  isVulnerable: String,
  email:String,
  is_active: {
    type: Number,
    enum: [0, 1],
    default: 1,
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
  updatedAt: {
    type: Date,
  },
  approved: {
    type: Number,
    enum: [0, 1],
    default: 0,
  },
  is_completed: {
    type: Number,
    enum: [0, 1],
    default: 0,
  },
  update: {
    type: Number,
    enum: [0, 1],
    default: 0,
  },
  createdBy: String,
  updatedBy: String,
  reject: {
    type: Number,
    enum: [0, 1],
    default: 0,
  },
  approvedAt: {
    type: Date,
  },
  approvedBY: String,
  rejectionSummary: String,
  updateStatus: {},
  is_ActiveApproved: {
    type: Number,
    enum: [0, 1],
    default: 1,
  },
  updateCount: {
    type: Number,
    default: 0,
  },  
  is_ActiveSummary: String,
  ApprovedStatus: {},
  is_ActiveRejectSummary: String,
  is_ActiveReject: {
    type: Number,
    enum: [0, 1],
    default: 0,
  }

});


module.exports = updateShgMemberSchema;